[tool.poetry]
name = "citc"
version = "0.1.0"
description = ""
authors = ["Matt Williams <matt@milliams.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
mypy = "^0.760"
pytest-mock = "^1.13.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
black = {version = "*", allow-prereleases = true}
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
