[tool.poetry]
name = "citc"
version = "0.3.10"
description = ""
authors = ["Matt Williams <matt@milliams.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.14"
PyYaml = "^5.3"
oci = "^2.18.0"
tabulate = "^0.8.6"
google-api-python-client = "^1.10.0"
google-auth-oauthlib = "^0.4.1"
boto3-stubs = {version = "^1.14", extras = ["ec2", "route53"]}

[tool.poetry.dev-dependencies]
pytest = "^5.4"
pytest-mock = "^3.2.0"
black = {version = "^19.10b0", allow-prereleases = true}
mypy = "^0.782"
flake8 = "^3.7.9"
moto = "^1.3.15"
coverage = "^5.0.3"
mebula = {version = "^0.2.7", allow-prereleases = true, extras = ["azure", "google", "oracle"]}

[tool.poetry.scripts]
watchdog = 'citc.watchdog:main'
list_nodes = 'citc.list_nodes:main'

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
