name: Release

on:
  push:
    branches:
      - master
    tags:
    - '*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: pip install poetry
      - name: Build package
        run: poetry build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          # body:  # TODO Read this from the CHANGELOG
          draft: false
          prerelease: false
      - name: Upload packages
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./citc-${{ github.ref }}-py3-none-any.whl
            asset_name: citc-${{ github.ref }}-py3-none-any.whl
            asset_content_type: application/zip
